version: 2.1

orbs:
  vault: contentful/vault@1

jobs:
  test:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - run: npm run test
  release:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'semantic-release-ecosystem'
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          context:
            - vault
          requires:
            - test
