version: 2.1

orbs:
  vault: contentful/vault@1

jobs:
  test:
    docker:
      - image: cimg/node:20.19.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm ci --prefer-offline
      - run: npm run build
      - run: npm run test
  release:
    docker:
      - image: cimg/node:20.19.4
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: "semantic-release-ecosystem"
      - run: npm ci  --prefer-offline
      - run: npm run build
      - run: npm run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          context:
            - vault
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - beta
